version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: baloghlan
      POSTGRES_PASSWORD: baloghlan1234
      POSTGRES_DB: iticket_db
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: baloghlan
      MINIO_ROOT_PASSWORD: baloghlan1234
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=baloghlan
      - GF_SECURITY_ADMIN_PASSWORD=baloghlan1234
    networks:
      - backend-network

  loki:
    image: grafana/loki:2.8.1
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./src/main/resources/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./path/on/host/tmp/loki:/tmp/loki
    networks:
      - backend-network

  promtail:
    image: grafana/promtail:2.8.1
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yaml -config.expand-env=true
    volumes:
      - /var/log:/var/log
      - ./src/main/resources/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    networks:
      - backend-network

volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
