spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/iticket_db
    username: baloghlan
    password: baloghlan1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080