spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/iticket_db
    username: baloghlan
    password: baloghlan1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  client:
    countriesnow:
      credentials:
        url: https://countriesnow.space/api/v0.1/

server:
  port: 8080