spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/iticket_db
    username: baloghlan
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  client:
    countriesnow:
      credentials:
        url: https://countriesnow.space/api/v0.1/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8090