spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/iticket_db
    username: baloghlan
    password: baloghlan1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: qasimovbaloglan13@gmail.com
    password: lygrnnutpejaguwo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  client:
    countriesnow:
      credentials:
        url: https://countriesnow.space/api/v0.1/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080